-- =========================================================================================
-- MOCK DATA SCRIPT FOR PROJECT FREIGHT JOBS
-- This script generates sample AIR, SEA, and ROAD jobs with child details.
-- Run this in an Oracle environment to populate the database for testing.
-- Make sure to REPLACE 999 WITH YOUR ACTUAL PROJECT_POID before running!
-- =========================================================================================

-- Set your target project POID here
DEFINE TARGET_PROJECT_POID = 999;
-- Ensure constraints don't fail by using a valid company POID if required
DEFINE COMPANY_POID = 1;

-- =====================================================================
-- 1. Create AIR Freight Jobs
-- =====================================================================
INSERT INTO FF_MANIEST_HDR (
    TRANSACTION_POID, TRANSACTION_DATE, COMPANY_POID, PROJECT_POID,
    FF_JOBNO, FF_JOBTYPE, JOB_STATUS, DELETED,
    AWPORT_OF_LOAD, AWPORT_OF_UNLOAD, FLIGHT_DATE, FLIGHT_NO,
    TOTAL_NO_OF_PACKS, TOTAL_WEIGHT, TOTAL_VOLUME, CARRIER_CODE, CARGO_DESCRIPTION,
    MASTER_BL_NO, HOUSE_BL_NO, DOCUMENT_STATUS
) VALUES (
    FF_MANIEST_HDR_SEQ.NEXTVAL, SYSDATE, &COMPANY_POID, &TARGET_PROJECT_POID,
    'AIR-JOB-001', 'AIR', 'IN_PROGRESS', 'N',
    'JFK', 'DXB', SYSDATE + 5, 'EK202',
    10, 500.0, 2.5, 'EK', 'Electronics and IT Equipment',
    'MAWB-123456', 'HAWB-987654', 'APPROVED'
);

INSERT INTO FF_MANIEST_HDR (
    TRANSACTION_POID, TRANSACTION_DATE, COMPANY_POID, PROJECT_POID,
    FF_JOBNO, FF_JOBTYPE, JOB_STATUS, DELETED,
    AWPORT_OF_LOAD, AWPORT_OF_UNLOAD, FLIGHT_DATE, FLIGHT_NO,
    TOTAL_NO_OF_PACKS, TOTAL_WEIGHT, TOTAL_VOLUME, CARRIER_CODE, CARGO_DESCRIPTION,
    MASTER_BL_NO, HOUSE_BL_NO, DOCUMENT_STATUS
) VALUES (
    FF_MANIEST_HDR_SEQ.NEXTVAL, SYSDATE, &COMPANY_POID, &TARGET_PROJECT_POID,
    'AIR-JOB-002', 'AIR', 'COMPLETED', 'N',
    'LHR', 'DXB', SYSDATE - 2, 'BA105',
    5, 250.0, 1.2, 'BA', 'Medical Supplies',
    'MAWB-777888', 'HAWB-555444', 'RECEIVED'
);

-- Add Package Details for AIR Jobs
-- For the first AIR job
INSERT INTO FF_MANIFEST_AIR_PKG_DETAILS (
    TRANSACTION_POID, DET_ROW_ID, NO_OF_PACKS, PACK_UNIT,
    TOTAL_WEIGHT, TOTAL_VOLUME, LENGTH, WIDTH, HEIGHT,
    DESCRIPTION, DOC_STATUS
) VALUES (
    (SELECT MAX(TRANSACTION_POID) - 1 FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'AIR' AND PROJECT_POID = &TARGET_PROJECT_POID),
    1, 5, 'BOX', 250.0, 1.25, 100, 50, 50, 'Servers Part 1', 'APPROVED'
);

INSERT INTO FF_MANIFEST_AIR_PKG_DETAILS (
    TRANSACTION_POID, DET_ROW_ID, NO_OF_PACKS, PACK_UNIT,
    TOTAL_WEIGHT, TOTAL_VOLUME, LENGTH, WIDTH, HEIGHT,
    DESCRIPTION, DOC_STATUS
) VALUES (
    (SELECT MAX(TRANSACTION_POID) - 1 FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'AIR' AND PROJECT_POID = &TARGET_PROJECT_POID),
    2, 5, 'BOX', 250.0, 1.25, 100, 50, 50, 'Servers Part 2', 'APPROVED'
);

-- For the second AIR job
INSERT INTO FF_MANIFEST_AIR_PKG_DETAILS (
    TRANSACTION_POID, DET_ROW_ID, NO_OF_PACKS, PACK_UNIT,
    TOTAL_WEIGHT, TOTAL_VOLUME, LENGTH, WIDTH, HEIGHT,
    DESCRIPTION, DOC_STATUS, DELIVERY_DATE
) VALUES (
    (SELECT MAX(TRANSACTION_POID) FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'AIR' AND PROJECT_POID = &TARGET_PROJECT_POID),
    1, 5, 'PLT', 250.0, 1.2, 120, 80, 100, 'Vaccines', 'RECEIVED', SYSDATE - 1
);


-- =====================================================================
-- 2. Create SEA Freight Jobs
-- =====================================================================
INSERT INTO FF_MANIEST_HDR (
    TRANSACTION_POID, TRANSACTION_DATE, COMPANY_POID, PROJECT_POID,
    FF_JOBNO, FF_JOBTYPE, JOB_STATUS, DELETED,
    MOTHER_VSL_LOADPORT_POID, MOTHER_VSL_UNLOADPORT_POID,
    MOTHER_VSL_SAIL_DATE, MOTHER_VSL_ETA, MOTHER_VSL_NAME,
    TOTAL_WEIGHT, TOTAL_VOLUME, CARGO_DESCRIPTION,
    MASTER_BL_NO, HOUSE_BL_NO, DOCUMENT_STATUS
) VALUES (
    FF_MANIEST_HDR_SEQ.NEXTVAL, SYSDATE, &COMPANY_POID, &TARGET_PROJECT_POID,
    'SEA-JOB-001', 'SEA', 'IN_PROGRESS', 'N',
    101, 202,
    SYSDATE - 10, SYSDATE + 20, 'EVER GIVEN',
    25000.0, 60.5, 'Construction Materials',
    'SEA-MBL-001', 'SEA-HBL-001', 'PENDING'
);

INSERT INTO FF_MANIEST_HDR (
    TRANSACTION_POID, TRANSACTION_DATE, COMPANY_POID, PROJECT_POID,
    FF_JOBNO, FF_JOBTYPE, JOB_STATUS, DELETED,
    MOTHER_VSL_LOADPORT_POID, MOTHER_VSL_UNLOADPORT_POID,
    MOTHER_VSL_SAIL_DATE, MOTHER_VSL_ETA, MOTHER_VSL_NAME,
    TOTAL_WEIGHT, TOTAL_VOLUME, CARGO_DESCRIPTION,
    MASTER_BL_NO, HOUSE_BL_NO, DOCUMENT_STATUS
) VALUES (
    FF_MANIEST_HDR_SEQ.NEXTVAL, SYSDATE, &COMPANY_POID, &TARGET_PROJECT_POID,
    'SEA-JOB-002', 'SEA', 'PLANNED', 'N',
    303, 202,
    SYSDATE + 5, SYSDATE + 35, 'MSC GULSÜN',
    15000.0, 30.0, 'Automotive Parts',
    'SEA-MBL-002', 'SEA-HBL-002', 'DRAFT'
);

-- Add Container Details for SEA Jobs
-- For the first SEA job
INSERT INTO FF_MANIEST_CONTAINER_DTL (
    TRANSACTION_POID, DET_ROW_ID, CONTAINER_NO, CONTAINER_SIZE,
    CONTAINER_SEAL_NO, NO_OF_PACKS, PACK_UNIT, GRS_WEIGHT, GRS_VOLUME,
    CARGO_DESCRIPTION, DOC_STATUS
) VALUES (
    (SELECT MAX(TRANSACTION_POID) - 1 FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'SEA' AND PROJECT_POID = &TARGET_PROJECT_POID),
    1, 'MSCU1234567', '40HC',
    'SL-999888', 20, 'PLT', 12500.0, 30.25,
    'Steel Pipes', 'PENDING'
);

INSERT INTO FF_MANIEST_CONTAINER_DTL (
    TRANSACTION_POID, DET_ROW_ID, CONTAINER_NO, CONTAINER_SIZE,
    CONTAINER_SEAL_NO, NO_OF_PACKS, PACK_UNIT, GRS_WEIGHT, GRS_VOLUME,
    CARGO_DESCRIPTION, DOC_STATUS
) VALUES (
    (SELECT MAX(TRANSACTION_POID) - 1 FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'SEA' AND PROJECT_POID = &TARGET_PROJECT_POID),
    2, 'MSCU7654321', '40HC',
    'SL-999889', 20, 'PLT', 12500.0, 30.25,
    'Cement Bags', 'PENDING'
);

-- For the second SEA job
INSERT INTO FF_MANIEST_CONTAINER_DTL (
    TRANSACTION_POID, DET_ROW_ID, CONTAINER_NO, CONTAINER_SIZE,
    CONTAINER_SEAL_NO, NO_OF_PACKS, PACK_UNIT, GRS_WEIGHT, GRS_VOLUME,
    CARGO_DESCRIPTION, DOC_STATUS
) VALUES (
    (SELECT MAX(TRANSACTION_POID) FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'SEA' AND PROJECT_POID = &TARGET_PROJECT_POID),
    1, 'CMAU1122334', '20ST',
    'SL-111222', 10, 'BOX', 15000.0, 30.0,
    'Engine Components', 'DRAFT'
);


-- =====================================================================
-- 3. Create ROAD Freight Jobs
-- =====================================================================
INSERT INTO FF_MANIEST_HDR (
    TRANSACTION_POID, TRANSACTION_DATE, COMPANY_POID, PROJECT_POID,
    FF_JOBNO, FF_JOBTYPE, JOB_STATUS, DELETED,
    TRUCK_TRANSPORT_FROM, TRUCK_TRANSPORT_TO, MOTHER_VSL_ETA,
    TOTAL_WEIGHT, TOTAL_VOLUME, CARGO_DESCRIPTION,
    MASTER_BL_NO, DOCUMENT_STATUS
) VALUES (
    FF_MANIEST_HDR_SEQ.NEXTVAL, SYSDATE, &COMPANY_POID, &TARGET_PROJECT_POID,
    'ROAD-JOB-001', 'ROAD', 'COMPLETED', 'N',
    'Jeddah Port', 'Riyadh Warehouse', SYSDATE - 1,
    8000.0, 15.0, 'Furniture',
    'ROAD-BL-001', 'DELIVERED'
);

INSERT INTO FF_MANIEST_HDR (
    TRANSACTION_POID, TRANSACTION_DATE, COMPANY_POID, PROJECT_POID,
    FF_JOBNO, FF_JOBTYPE, JOB_STATUS, DELETED,
    TRUCK_TRANSPORT_FROM, TRUCK_TRANSPORT_TO, MOTHER_VSL_ETA,
    TOTAL_WEIGHT, TOTAL_VOLUME, CARGO_DESCRIPTION,
    MASTER_BL_NO, DOCUMENT_STATUS
) VALUES (
    FF_MANIEST_HDR_SEQ.NEXTVAL, SYSDATE, &COMPANY_POID, &TARGET_PROJECT_POID,
    'ROAD-JOB-002', 'ROAD', 'IN_PROGRESS', 'N',
    'Dammam Port', 'Riyadh Warehouse', SYSDATE + 1,
    12000.0, 20.0, 'Heavy Machinery',
    'ROAD-BL-002', 'IN_TRANSIT'
);

-- Add Truck Details for ROAD Jobs
-- For the first ROAD job
INSERT INTO FF_MANIFEST_TRUCK_DTL (
    TRANSACTION_POID, DET_ROW_ID, BL_AWB_NUMBER, TRUCK_NUMBER,
    BAYAN_NUMBER, BAYAN_MODE, ETA,
    DUTY_AMOUNT, VAT_AMOUNT, TOTAL_PAID_AMOUNT,
    SUBMITTED_DATE, PAYMENT_DATE, DOCUMENT_STATUS
) VALUES (
    (SELECT MAX(TRANSACTION_POID) - 1 FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'ROAD' AND PROJECT_POID = &TARGET_PROJECT_POID),
    1, 'ROAD-BL-001', 'TRK-9988',
    'BAY-1001', 'IMPORT', SYSDATE - 1,
    500.0, 150.0, 650.0,
    SYSDATE - 3, SYSDATE - 2, 'CLEARED'
);

-- For the second ROAD job
INSERT INTO FF_MANIFEST_TRUCK_DTL (
    TRANSACTION_POID, DET_ROW_ID, BL_AWB_NUMBER, TRUCK_NUMBER,
    BAYAN_NUMBER, BAYAN_MODE, ETA,
    DUTY_AMOUNT, VAT_AMOUNT, TOTAL_PAID_AMOUNT,
    SUBMITTED_DATE, DOCUMENT_STATUS
) VALUES (
    (SELECT MAX(TRANSACTION_POID) FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'ROAD' AND PROJECT_POID = &TARGET_PROJECT_POID),
    1, 'ROAD-BL-002', 'TRK-1122',
    'BAY-1002', 'IMPORT', SYSDATE + 1,
    1500.0, 450.0, 0.0,
    SYSDATE - 1, 'PENDING_PAYMENT'
);


-- =====================================================================
-- 4. Create BAYAN Details for AIR/SEA Jobs
-- =====================================================================
-- Add Bayan for the completed AIR job
INSERT INTO FF_MANIFEST_BAYAN_DTL (
    TRANSACTION_POID, DET_ROW_ID, BL_AWB_NUMBER, BAYAN_NUMBER, BAYAN_MODE,
    DUTY_AMOUNT, VAT_AMOUNT, TOTAL_PAID_AMOUNT,
    SUBMITTED_DATE, PAYMENT_DATE, EXPIRY_DATE
) VALUES (
    (SELECT MAX(TRANSACTION_POID) FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'AIR' AND JOB_STATUS = 'COMPLETED' AND PROJECT_POID = &TARGET_PROJECT_POID),
    1, 'MAWB-777888', 'BAY-AIR-101', 'IMPORT',
    100.0, 50.0, 150.0,
    SYSDATE - 5, SYSDATE - 4, SYSDATE + 30
);

-- Add Bayan for the in-progress SEA job
INSERT INTO FF_MANIFEST_BAYAN_DTL (
    TRANSACTION_POID, DET_ROW_ID, BL_AWB_NUMBER, BAYAN_NUMBER, BAYAN_MODE,
    DUTY_AMOUNT, VAT_AMOUNT, TOTAL_PAID_AMOUNT,
    SUBMITTED_DATE, EXPIRY_DATE
) VALUES (
    (SELECT MAX(TRANSACTION_POID) FROM FF_MANIEST_HDR WHERE FF_JOBTYPE = 'SEA' AND JOB_STATUS = 'IN_PROGRESS' AND PROJECT_POID = &TARGET_PROJECT_POID),
    1, 'SEA-MBL-001', 'BAY-SEA-202', 'IMPORT',
    2500.0, 1250.0, 0.0,
    SYSDATE - 1, SYSDATE + 14
);

COMMIT;
DBMS_OUTPUT.PUT_LINE('Mock data inserted successfully!');
